spring:
  application:
    name: turbine
server:
  port: 8007
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    port: 8008
turbine:
  app-config: auth,eureka,ribbon,hystrix,turbine,zuul
  cluster-name-expression: "default"
  combine-host-port: true
