spring:
  profiles: prod
  application:
    name: turbine
server:
  port: 8007
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: '*'
    jmx:
      exposure:
        include: '*'
  server:
    port: 8008
  endpoint:
    health:
      show-details: always
      enabled: true
turbine:
  app-config: auth,eureka,ribbon,hystrix,turbine,zuul
  cluster-name-expression: new String('default')
  combine-host-port: true
