spring:
  cloud:
    config:
      fail-fast: false
      discovery:
        enabled: true
        service-id: config
      server:
        git:
          uri: https://github.com/REP3/rep3-cloud.git
          search-paths:
          - aconfigs
  application:
    name: config
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
    jmx:
      exposure:
        include: "*"
