spring:
  application:
    name: auth
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
    jmx:
      exposure:
        include: "*"
