spring:
  profiles: peer1
  application:
    name: eureka
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
