spring:
  profiles: dev
  application:
    name: auth
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
