spring:
  application:
    name: hystrix
server:
  port: 8006
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
